# This is an example Mocha config containing every Mocha option plus others.
allow-uncaught: false
async-only: false
bail: false
check-leaks: false
color: true
delay: false
diff: true
exit: true
extension: ["js"]
fail-zero: true
require:
  - "@babel/polyfill"
  - "@babel/register"

timeout: 100000 # same as "timeout: '2s'"

trace-warnings: true # node flags ok
ui: "tdd"
